import type { TranslationValue } from '../types'

const common = {
  statusCurrent: 'Current', statusUpdateAvailable: 'Update available', statusUnknown: 'Unknown', statusUpdating: 'Updating', statusRollback: 'Rolled back', statusFailure: 'Update failed', packagedDigest: 'Packaged digest', deployedDigest: 'Deployed digest', version: 'Bundle version', fileCount: 'Files', ftpSecurity: 'FTPS security', ftpRemotePath: 'Remote server path', ftpUsername: 'FTPS username', ftpPassword: 'FTPS password', maintenanceToken: 'Maintenance token', passwordPlaceholder: 'Enter to save or replace', tokenPlaceholder: 'Enter to save or replace', saveCredentials: 'Save credentials', clearCredentials: 'Delete saved credentials', credentialsStored: 'Credentials are stored securely by the operating system.', credentialsMissing: 'Deployment credentials are not saved.', encryptionUnavailable: 'Secure credential storage is unavailable on this device.', recheck: 'Check now', update: 'Update server', confirmUpdate: 'Update the MDB server now? Database migrations cannot be undone by restoring files.', maintenanceNote: 'Every update requires explicit confirmation. Your BluePLM session token alone cannot deploy files.', statusLabel: 'Status', resultSuccess: 'MDB server updated successfully.', updateAvailableNotification: 'A new MDB server update is available.', unauthorized: 'Only an organization owner or administrator can update the MDB server.', invalidMaintenanceToken: 'The maintenance token was rejected.', missingCredentials: 'Save the FTPS profile, password, and maintenance token before updating.', healthMismatch: 'The updated server did not report the expected bundle.', genericFailure: 'The MDB server update could not be completed.',
} as const

export const settingsMdbServerTranslations: Record<string, TranslationValue> = {
  en: { ...common, title: 'MDB Server', description: 'Check and explicitly update the deployed MDB server bundle.', credentialsTitle: 'Deployment credentials', credentialsDescription: 'FTPS credentials upload PHP files. The maintenance token authorizes database migrations only.', ftpUrl: 'FTPS server URL', explicitTls: 'Explicit TLS', implicitTls: 'Implicit TLS' },
  de: { ...common, title: 'MDB-Server', description: 'Das bereitgestellte MDB-Serverpaket prüfen und ausdrücklich aktualisieren.', credentialsTitle: 'Bereitstellungs-Zugangsdaten', credentialsDescription: 'FTPS-Zugangsdaten laden PHP-Dateien hoch. Das Wartungstoken autorisiert nur Datenbankmigrationen.', ftpUrl: 'FTPS-Server-URL', explicitTls: 'Explizites TLS', implicitTls: 'Implizites TLS' },
  es: { ...common, title: 'Servidor MDB', description: 'Comprobar y actualizar explícitamente el paquete del servidor MDB desplegado.', credentialsTitle: 'Credenciales de despliegue', credentialsDescription: 'Las credenciales FTPS cargan archivos PHP. El token de mantenimiento solo autoriza migraciones de base de datos.', ftpUrl: 'URL del servidor FTPS', explicitTls: 'TLS explícito', implicitTls: 'TLS implícito' },
  fr: { ...common, title: 'Serveur MDB', description: 'Vérifier et mettre explicitement à jour le paquet du serveur MDB déployé.', credentialsTitle: 'Identifiants de déploiement', credentialsDescription: 'Les identifiants FTPS téléversent les fichiers PHP. Le jeton de maintenance autorise uniquement les migrations de base de données.', ftpUrl: 'URL du serveur FTPS', explicitTls: 'TLS explicite', implicitTls: 'TLS implicite' },
  pt: { ...common, title: 'Servidor MDB', description: 'Verifique e atualize explicitamente o pacote do servidor MDB implantado.', credentialsTitle: 'Credenciais de implantação', credentialsDescription: 'As credenciais FTPS enviam arquivos PHP. O token de manutenção autoriza apenas migrações do banco de dados.', ftpUrl: 'URL do servidor FTPS', explicitTls: 'TLS explícito', implicitTls: 'TLS implícito' },
  'zh-CN': { ...common, title: 'MDB 服务器', description: '检查并明确更新已部署的 MDB 服务器软件包。', credentialsTitle: '部署凭据', credentialsDescription: 'FTPS 凭据用于上传 PHP 文件。维护令牌仅授权数据库迁移。', ftpUrl: 'FTPS 服务器 URL', explicitTls: '显式 TLS', implicitTls: '隐式 TLS' },
  'zh-TW': { ...common, title: 'MDB 伺服器', description: '檢查並明確更新已部署的 MDB 伺服器套件。', credentialsTitle: '部署憑證', credentialsDescription: 'FTPS 憑證用於上傳 PHP 檔案。維護權杖僅授權資料庫遷移。', ftpUrl: 'FTPS 伺服器 URL', explicitTls: '明確 TLS', implicitTls: '隱含 TLS' },
}
